### PR TITLE
Creation database sql AS

### PR DESCRIPTION
**Pull request by 20sisca**

### CODE REVIEW

**Review by ngiboureau — CHANGES_REQUESTED** [review]
u should delete the "sql" folder in "molonaviz"

Or...

```
from widgetpoint import WidgetPoint
  File "/home/fors/Projets/molonari/Molonari-2022/Molonari_2021/ihm/molonaviz/widgetpoint.py", line 17, in <module>
    from sql.creationinput import DataBase
ModuleNotFoundError: No module named 'sql'
```

**Comment by fabien-ors** [comment]
In order to speed up point importation procedure, you should use transaction / commit before inserting measures in the SQL table. Do not forget to rollback the transaction in case of insertion request problem.

**Comment by fabien-ors** [comment]
A file is currently missing in sql folder ??
```
    from widgetpoint import WidgetPoint
  File "/home/fors/Projets/molonari/Molonari-2022/Molonari_2021/ihm/molonaviz/widgetpoint.py", line 17, in <module>
    from sql.creationinput import DataBase
ModuleNotFoundError: No module named 'sql'
```

**Comment by fabien-ors** [comment]
Molonaviz is launching => OK but the startup procedure is very long.
Could it be possible to plug the DB conversion V1 => SQL to a menu action under Study main menu ?
First, the user open the study V1 as usual, then he chooses to convert the current open study using the menu (ask the SQL file destination folder in a small window).

The mainSql.py application in small_application_sql doesn't work. Could you fix please ?
It seems that some file names still start with a upper case.
```
  File "/home/fors/Projets/molonari/Molonari-2022/Molonari_2021/ihm/small_application_sql/mainSql.py", line 14, in <module>
    from studyDb import StudyDb
ModuleNotFoundError: No module named 'studyDb'
```

**Review by GVigne — APPROVED** [review]

**Comment by GVigne** [comment]
Nevermind, there is a problem in your _WaterFlowDb.py_ file, when you are making the CREATE statement. There is an additional coma at the end of the _Date_ line, so the query fails.

**Review by ngiboureau — APPROVED** [review]

**Pull request merged**
