### PR TITLE
IHM1_F10

### PR DESCRIPTION
**Pull request by chengfenggu2000**
IHM1_F10
Now we can keep in memory the the last script in the cleanup window and show it as default next time

### CODE REVIEW

**Review by fabien-ors — DISMISSED** [review]
The saved python script should be stored in the study_2022/PointXX directory - not in the source directory. If the previous saved script doesn't exist (for example, after the creation of a new study), the cleanup dialog should show an example of some python command example acting on dft and dfp pandaframe.
Please remove spurious *.txt files in molonaviz source directory

**Comment by chengfenggu2000** [comment]
I remove the save_text.txt in \ihm\molonaviz, and the new save_text.txt will be read from(saved in) study_2022/PointXX. If this save_text.txt doesn't exist, we will show the sample_text.txt (Which is still in \ihm\molonaviz), and once you click "OK", data will be cleaned following your script and a save_text.txt will be created in study_2022/PointXX.

**Comment by fabien-ors** [comment]
> I remove the save_text.txt in \ihm\molonaviz, and the new save_text.txt will be read from(saved in) study_2022/PointXX. If this save_text.txt doesn't exist, we will show the sample_text.txt (Which is still in \ihm\molonaviz), and once you click "OK", data will be cleaned following your script and a save_text.txt will be created in study_2022/PointXX.

The script shouldn't be saved if its execution fails. In that case, the cleanup window should remain open.

**Comment by chengfenggu2000** [comment]
OK get it! I will modify this tomorrow morning. 
Best, 
Chengfeng

**Comment by chengfenggu2000** [comment]
A version satifying the currrent needs "The script shouldn't be saved if its execution fails. In that case, the cleanup window should remain open."

**Comment by jcurbanog** [comment]
scrpt.py file should be also eliminated in case of error while importing.

**Comment by chengfenggu2000** [comment]
now the scrpt.py file will be eliminated correctly

**Review by jcurbanog — APPROVED** [review]
Feature works as expected

**Pull request merged**
