### PR TITLE
IHM1_Compute

### PR DESCRIPTION
**Pull request by Jia-FU-Soline**
Fenetre Compute sans base de données

### CODE REVIEW

**Review by fabien-ors — CHANGES_REQUESTED** [review]
Please, comment the code in english language.

**Comment by fabien-ors** [comment]
Ok. Nice job !
Please, could you update vertical header names (Layer 4, Layer 5) in place of "4", "5" exactly as Layer 1, Layer 2 ?

**Comment by Jia-FU-Soline** [comment]
> Ok. Nice job !
> Please, could you update vertical header names (Layer 4, Layer 5) in place of "4", "5" exactly as Layer 1, Layer 2 ?

De mon côté ça affiche déjà comme Layer4, Layer5, etc.

**Comment by fabien-ors** [comment]
The "Run" button should be active even if the "Execute Inversion Before" is unchecked. (in order to launch the direct model)

**Comment by fabien-ors** [comment]
If the box "Execute Inversion Before" is **unchecked**, the Run button should only launch the direct model (no MCMC).

**Review by fabien-ors — APPROVED** [review]

**Pull request merged**
