### PR TITLE
IHM_C9

### PR DESCRIPTION
**Pull request by chengfenggu2000**
Now if the computation package pyheatmy is not installed, a warning will be generated automaticly showing how to install pyheatmy, and after that the molonaviz will still be launched

### CODE REVIEW

**Review by MaxFressonnet — COMMENTED** [review]
It works, when we try to open molonaviz without pyheatmy, the warning is displayed, but :
 - when we click 'OK', a second warning is displayed, and only when we cick 'OK' again, molonaviz is launched, is it normal ?
 - when we define the ban and try to compute without pyheatmy, molonaviz crashes

**Comment by chengfenggu2000** [comment]
The reason why we have 2 warning, is that there is in fact 2 .py script who use pyheatmy(compute.py and point.py), and we mentioned in each warning where the problem is. Two warning is just to show the full dependency. If we only set one warning(in compute.py or in point.py), once someone change the file where we set the warning in the future, this character will lose.

For the crash, we already mentioned in the warning that compute part is not available, I think this is enough, because once you get the warning you will try to install pyheat my, rather than keep using it in the wrong way.

**Comment by fabien-ors** [comment]
We can display only one warning (at the IHM startup) and prevent the software from crashing all other times. 
We can import pyheatmy in mainwindow just for testing if it's available.

**Comment by chengfenggu2000** [comment]
OK! 
Here is the modified version, now only one warning will be should when open molonaviz without pyheatmy. And inside Molonaviz, if you click compute button there will show another warning telling you its not usable.

**Review by MaxFressonnet — APPROVED** [review]

**Pull request merged**
